### PR TITLE
fix: uncomment nomidot tasks

### PR DESCRIPTION
**Pull request by yjkimjunior**
check between old and new api and handle accordingly

related: https://github.com/paritytech/Nomidot/pull/236

### CODE REVIEW

**Comment by Tbaut** [comment]
Not sure it's related, I got a couple:
```bash
Error: No Node for the model Session with value 21 for index found.
    at BatchedGraphQLClient.<anonymous> (/home/thib/github/paritytech/Nomidot/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
    at step (/home/thib/github/paritytech/Nomidot/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/home/thib/github/paritytech/Nomidot/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/home/thib/github/paritytech/Nomidot/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  result: { data: null, errors: [ [Object] ], status: 200 }
```

For some reason I had no era created, not sure if it's my setup.. it's a local node running on --dev. I didn't have any nomination either.

Staking row were created successfully.

**Comment by yjkimjunior** [comment]
probably you don't have a Session with Index 21 on your local prisma?

**Comment by Tbaut** [comment]
> probably you don't have a Session with Index 21 on your local prisma?

Ok by why? I started the sync from block 0, I got this for every single session.

**Comment by yjkimjunior** [comment]
ah, i didn't realize you got this for every single session.

**Pull request merged**
