### PR TITLE
Track council members

### PR DESCRIPTION
**Pull request by Tbaut**
Today wasn't my day, I've spent hours to get this many-to-many to work.
We're creating council rows everytime the event "newSet" is called. Linking members to the council set, or creating members and linking them.

A member can be part of several sets, a council can have several members.

### CODE REVIEW

**Comment by Tbaut** [comment]
Oops, OK I'll look into that later today.

**Comment by yjkimjunior** [comment]
bump @niklabh , would really like to have this one merged before starting v1.5 sync!

**Comment by yjkimjunior** [comment]
looks good, will do another thoroguh review in the morning before beginning 1.5 sync! thanks you @niklabh @Tbaut !

**Comment by yjkimjunior** [comment]
looks good, will do another thorough review in the morning before beginning 1.5 sync! thanks you @niklabh @Tbaut !

**Pull request merged**
