### PR TITLE
Added types for bn.js. Other docker misc fixes

### PR DESCRIPTION
**Pull request by niklabh**
- types for bn.js
- dockerfile changes so that yarn only runs when dependencies has changed
- a yarn.lock file in node_watcher. please move root node.js project in seperate folder inside repo
- .dockerignore file so copy command dont copy node_modules

### CODE REVIEW

**Comment by Tbaut** [comment]
closes: https://github.com/paritytech/Nomidot/issues/175

**Comment by yjkimjunior** [comment]
> a yarn.lock file in node_watcher. please move root node.js project in seperate folder inside repo

how was this lock file generated? @niklabh

**Comment by amaurymartiny** [comment]
Follow-up questions:
- why is it actually needed?
- could we just copy the one in the root folder inside the docker image?

**Comment by niklabh** [comment]
Generated by deleting yarn.lock in root folder of the repo then running yarn in node_watcher

**Comment by niklabh** [comment]
> Follow-up questions:
> 
> * why is this lock file actually needed? could we just copy the one in the root folder inside the docker image?

File need to be copied inside docker to make the builds fast. 
yarn.lock in root should not be copied. First of all this is not possible in docker as dockerfile works only in current working directory. Also yarn.lock in root is different from the node_watcher folder as package.json is differenet. When yarn.lock is present in parent folder that is used. This will conflict with root folder project and node_watcher project.

**Comment by amaurymartiny** [comment]
Two things:
- I just saw https://github.com/polkadot-js/api/blob/master/CHANGELOG.md#131-feb-18-2020 (1st entry), I think types/bn.js could be removed now from package.json
- I still don't see how copying yarn.lock makes the build faster, but we can keep it. In this case, I would recommend to remove `back/node_watcher` from yarn workspaces

**Comment by niklabh** [comment]
Build is fast by using this dockerfile

FROM node:10

RUN mkdir -p /opt/app

RUN chown node:node /opt/app

WORKDIR /opt/app

# yarn.lock should be in node_watcher to be copied into docker
COPY --chown=node:node package.json .
COPY --chown=node:node yarn.lock .

USER node
# docker work on layered architecture. if there is no change in above lines .i.e. package.json and yarn.lock this will not run again making build super fast
RUN yarn

COPY --chown=node:node . .

CMD yarn start

**Pull request merged**
