### PR TITLE
docs: Writeup on Nomidot

### PR DESCRIPTION
**Pull request by yjkimjunior**

### CODE REVIEW

**Comment by amaurymartiny** [comment]
Is it still in progress? Not sure why CI is complaining, it seems to me everything is fine https://github.com/paritytech/Nomidot/blob/master/front/gatsby/src/ContextGate.tsx#L26

**Comment by yjkimjunior** [comment]
just marked in progress in case you wanted add/remove somethings, will probably think of something as the day goes on.

wrt CI, it seems I'm not admin either :/

**Comment by amaurymartiny** [comment]
> I'm not admin either

So we can't actually squash and merge... could you try rebasing or merging master?

**Comment by yjkimjunior** [comment]
let me quickly add a contributing guidline before we merge

**Comment by amaurymartiny** [comment]
For inspiration, we once wrote https://github.com/paritytech/substrate-light-ui/blob/master/CONTRIBUTING.md

**Comment by yjkimjunior** [comment]
oh perfect i'll just copy paste more or less

**Pull request merged**
