### PR TITLE
Added cluster to speed up block processing

### PR DESCRIPTION
**Pull request by niklabh**
Blocks are being processed from process.env.START_FROM to lastKnownBestFinalized

Blocks are processed one by one which takes time. We can leverage node js multi core processing with cluster module. cluster produces identical copy of running code with seperate stack, local variables and event loop. If number of cpu is 8 the block processing time will be reduced to 1/8 of the original. This code assume that block processing can be done out of order and in parallel.

Master and workers can be differentiated with cluster.isMaster cluster.isWorker flags.

I am dividing the blocks from start to end in equal batches of size end-start/numberOfCpus.
Processing different batch with formula

```
const batch = Math.floor((lastKnownBestFinalized - blockIndex) / cpuCount);
blockIndex = blockIndex + (cluster.worker.id - 1) * batch;
endAt = blockIndex + batch - 1;
```

In worker if am processing blockIndex to endAt. Then i am exiting the loop.

In master i am keeping the loop alive with getting waitFinalized each time as old logic. 

This code is not 100% tested and and should not be merged yet. Some corner cases are not covered. Same block could be processed multiple times.

Need to add code where you only want 1 process and not master worker as we dont want that during development. 

Please discuss and merge only after it is tested and cover all the corner cases.

### CODE REVIEW

**Comment by amaurymartiny** [comment]
> This code assume that block processing can be done out of order and in parallel.

This assumption does not hold. Example:

- Cluster 1: Blocks 1000-2000:
  - Block 1500: A new proposal gets created, with id `id_a`
- Cluster 2: Blocks 2000-30000:
  - Block 2000: Proposal `id_a`'s status gets updated

There's a high probablibility that cluster2 will process block 2000 before cluster1 processes block 1500. In that case, cluster2's task will not find proposal `id_a` in the DB.

**Comment by niklabh** [comment]
ah ok then closing

**Comment by amaurymartiny** [comment]
I think a more promising avenue we could explore is what @yjkimjunior  proposed: do an ETL directly from an archive node's key-value DB into prisma's SQL db. This would allow easily a 1000x speedup, since we bypass all network requests done at each block.

The tricky part is how to find a way to continuosly read from the archive node's key-value DB while it syncs.

Basically we now have 3 ways of doing it, ordered from the most elegant to least elegant, aka also from most work to least work on our side:
1. Wait for substrate-archive to be done, do an ETL from substrate-archive's DB to our chain DB
2. ETL from archive-node's kvdb to our chain DB
3. What we do currently: do a bunch of block-scoped tasks, increment block, write into our chain DB.

I don't want to depend on 1, it might take 2 weeks or 2 months. If 3 continues to give us problems, we could consider exploring 2. wdyt @niklabh @yjkimjunior?

**Comment by yjkimjunior** [comment]
I've never tried a RocksDB to Postgresql migration, but I dont imagine it's trivial especially with the way Substrate storage works. Given the resources we have at our disposal, I'd say we just hammer through with 3 until we are able to ship our respective projects, and if 1 is stilll not ready by then, then we revisit 2. 

3 is painful and manual right now but after we've synced the core parts I don't think the updates and resyncing will be as frequent. 

In terms of speed of syncing, I'd like to revisit the ideas of:

1. throw more CPUs at it
2. run more jobs in parallel from differnt START_FROM's

Both are pretty "dumb" from an engineering perspective, but would get the job done faster from a product perspective IMHO.

**Comment by amaurymartiny** [comment]
Some other optimizations:
- cache some `.at()`, i see multiple `api.query.system.events.at()`, they always return the same result.
- run tasks (not jobs) parallely, see https://github.com/paritytech/Nomidot/issues/111#issuecomment-578882139

> run more jobs in parallel from differnt START_FROM's

Wouldn't this also possibly run into inconsistencies like https://github.com/paritytech/Nomidot/pull/155#issuecomment-584164004?

**Comment by yjkimjunior** [comment]
> Wouldn't this also possibly run into inconsistencies like #155 (comment)?

ah 💩 yeah that's right

> cache some .at(), i see multiple api.query.system.events.at(), they always return the same result.

working on a PR that includes something like this, not caching but rather just checks if a new session started then only query the thing (eg rewards, validators, heartbeats only happen once a session).

> run tasks (not jobs) parallely

this one sounds in theory great but I'm not actually sure what a concrete implementation would look like. Would we group tasks at each level of the dependency graph into their own job and run those in parallel?

**Pull request closed without merging**
